version: "3"
volumes:
    node:
    vendor:
    db:
services:
    nginx:
        container_name: "nginx"
        build:
            context: ./docker/nginx
        depends_on:
            - app
        ports:
            - 80:80
        volumes:
            - ./:/src

    app:
        container_name: "app"
        build:
            context: ./docker/php
        depends_on:
            - mysql
        ports:
            - 5173:5173
        volumes:
            - ./src:/src
            - node:/src/node_modules
            - vendor:/src/vendor
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mysql:8.0.33
        command: --max_allowed_packet=32505856
        container_name: "mysql"
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel_event
        ports:
            - 3306:3306

    redis:
        image: redis:alpine
        container_name: "redis"
        ports:
            - 16379:6379
